---

- name: install - create group
  group:
    name={{ prometheus_consul_group }}
    state=present
    system=yes

- name: install - create user
  user:
    name={{  prometheus_consul_user }}
    group={{ prometheus_consul_group }}
    system=yes
    createhome=no

- name: already installed check
  stat: path={{ prometheus_consul_install_dir }}/consul_exporter
  register: binary_file

- name: install - checkout exporter consul
  git:
    repo={{ prometheus_consul_repo }}
    dest={{ prometheus_consul_build_folder }}
    version=master
    depth=1
    update=yes
    accept_hostkey=yes
    force=yes
    recursive=yes

- name: install - make consul exporter
  shell: make 
  args:
    chdir: "{{ prometheus_consul_build_folder }}"
  when: not binary_file.stat.exists

- name: install - make directories
  file:
    state=directory
    path={{ item }}
    owner={{ prometheus_consul_user }}
    group={{ prometheus_consul_group }}
    mode=0755
  with_items:
    - "{{ prometheus_consul_conf_dir }}"
    - "{{ prometheus_consul_log_dir }}"
    - "{{ prometheus_consul_install_dir }}"

- name: install - move binary
  command: mv {{ prometheus_consul_build_folder }}/consul_exporter {{ prometheus_consul_install_dir }}/
  args:
    creates: "{{ prometheus_consul_install_dir }}/consul_exporter"




